#ifndef CYNIDE_PARSER_H
#define CYNIDE_PARSER_H

#include <memory>
#include <string>
#include <vector>

#include <ast.h>
#include <stage.h>
#include <token.h>

/**
 * @class Parser
 * @brief Performs syntax analysis (parsing) on a stream of Tokens to produce an
 * Abstract Syntax Tree (AST).
 *
 * The Parser implements a Recursive Descent parser for the Cynide language
 * grammar. It consumes tokens generated by the Lexer and constructs ASTNode
 * representations.
 */
class Parser : public Stage {
public:
  /**
   * @brief Constructs a new Parser instance.
   * @param tokens A vector of tokens produced by the Lexer.
   */
  explicit Parser(std::vector<Token> tokens) : _tokens(std::move(tokens)) {}

  /**
   * @brief Parses the entire token stream into a Program AST node.
   *
   * Grammar:
   * @code
   * program -> statement* EOF
   * @endcode
   *
   * @return A unique_ptr to the root Program node.
   */
  std::unique_ptr<Program> parseProgram();

  /**
   * @brief Checks if the parser has encountered any syntax errors.
   * @return true if an error has occurred, false otherwise.
   */
  bool hasError() const override { return _error; }

  /**
   * @brief Retrieves the parser error message.
   * @return A string containing details of the parser error.
   */
  std::string errorMessage() const override { return _errorMessage; }

  /**
   * @brief Dumps a textual representation of the AST to stdout.
   * @param program The root node of the AST to print.
   */
  static void dumpAst(const std::unique_ptr<Program> &program);

private:
  std::vector<Token> _tokens;
  size_t _pos = 0;
  bool _error = false;
  std::string _errorMessage;

  /**
   * @brief Parses a single statement.
   *
   * Grammar:
   * @code
   * statement -> variableDecl
   *            | functionDef
   *            | ifElseStmt
   *            | whileStmt
   *            | forStmt
   *            | returnStmt
   *            | printStmt
   *            | assignStmt
   *            | exprStmt
   * @endcode
   *
   * @return A unique_ptr to the parsed StmtNode.
   */
  std::unique_ptr<StmtNode> parseStatement();

  /**
   * @brief Parses a variable declaration (`let` statement).
   *
   * Grammar:
   * @code
   * variableDecl -> "let" IDENTIFIER ( ":" typeAnnotation )? "=" expr
   * @endcode
   *
   * @return A unique_ptr to the parsed VariableDecl node.
   */
  std::unique_ptr<VariableDecl> parseVariableDecl();

  /**
   * @brief Parses a function definition (`fn` statement).
   *
   * Grammar:
   * @code
   * functionDef -> "fn" IDENTIFIER "(" ( IDENTIFIER ":" typeAnnotation ( ","
   * IDENTIFIER ":" typeAnnotation )* )? ")" "->" typeAnnotation ":" block
   * @endcode
   *
   * @return A unique_ptr to the parsed FunctionDef node.
   */
  std::unique_ptr<FunctionDef> parseFunctionDef();

  /**
   * @brief Parses an if/elif/else conditional statement.
   *
   * Grammar:
   * @code
   * ifElseStmt -> "if" expr ":" block ( "elif" expr ":" block )* ( "else" ":"
   * block )?
   * @endcode
   *
   * @return A unique_ptr to the parsed IfElseStmt node.
   */
  std::unique_ptr<IfElseStmt> parseIfElseStmt();

  /**
   * @brief Parses a while loop statement.
   *
   * Grammar:
   * @code
   * whileStmt -> "while" expr ":" block
   * @endcode
   *
   * @return A unique_ptr to the parsed WhileStmt node.
   */
  std::unique_ptr<WhileStmt> parseWhileStmt();

  /**
   * @brief Parses a for loop statement.
   *
   * Grammar:
   * @code
   * forStmt -> "for" IDENTIFIER "in" "range" "(" expr ( "," expr )? ")" ":"
   * block
   * @endcode
   *
   * @return A unique_ptr to the parsed ForStmt node.
   */
  std::unique_ptr<ForStmt> parseForStmt();

  /**
   * @brief Parses a return statement.
   *
   * Grammar:
   * @code
   * returnStmt -> "return" expr?
   * @endcode
   *
   * @return A unique_ptr to the parsed ReturnStmt node.
   */
  std::unique_ptr<ReturnStmt> parseReturnStmt();

  /**
   * @brief Parses a print statement.
   *
   * Grammar:
   * @code
   * printStmt -> "print" "(" ( expr ( "," expr )* )? ")"
   * @endcode
   *
   * @return A unique_ptr to the parsed PrintStmt node.
   */
  std::unique_ptr<PrintStmt> parsePrintStmt();

  /**
   * @brief Parses either an assignment statement or an expression statement.
   *
   * Grammar:
   * @code
   * assignStmt -> IDENTIFIER "=" expr
   * exprStmt   -> expr
   * @endcode
   *
   * @return A unique_ptr to the parsed StmtNode.
   */
  std::unique_ptr<StmtNode> parseAssignOrExprStmt();

  /**
   * @brief Parses a block statement (indented block).
   *
   * Grammar:
   * @code
   * block -> INDENT statement+ DEDENT
   * @endcode
   *
   * @return A unique_ptr to the parsed Block node.
   */
  std::unique_ptr<Block> parseBlock();

  /**
   * @brief Parses an expression (lowest precedence level).
   *
   * Grammar:
   * @code
   * expr -> or
   * @endcode
   *
   * @return A unique_ptr to the parsed ExprNode.
   */
  std::unique_ptr<ExprNode> parseExpr();

  /**
   * @brief Parses a logical OR expression.
   *
   * Grammar:
   * @code
   * or -> and ( "or" and )*
   * @endcode
   *
   * @return A unique_ptr to the parsed ExprNode.
   */
  std::unique_ptr<ExprNode> parseOr();

  /**
   * @brief Parses a logical AND expression.
   *
   * Grammar:
   * @code
   * and -> equality ( "and" equality )*
   * @endcode
   *
   * @return A unique_ptr to the parsed ExprNode.
   */
  std::unique_ptr<ExprNode> parseAnd();

  /**
   * @brief Parses an equality expression (==, !=).
   *
   * Grammar:
   * @code
   * equality -> comparison ( ( "==" | "!=" ) comparison )*
   * @endcode
   *
   * @return A unique_ptr to the parsed ExprNode.
   */
  std::unique_ptr<ExprNode> parseEquality();

  /**
   * @brief Parses a comparison expression (<, >, <=, >=).
   *
   * Grammar:
   * @code
   * comparison -> addSub ( ( "<" | ">" | "<=" | ">=" ) addSub )*
   * @endcode
   *
   * @return A unique_ptr to the parsed ExprNode.
   */
  std::unique_ptr<ExprNode> parseComparison();

  /**
   * @brief Parses an additive expression (+, -).
   *
   * Grammar:
   * @code
   * addSub -> mulDivMod ( ( "+" | "-" ) mulDivMod )*
   * @endcode
   *
   * @return A unique_ptr to the parsed ExprNode.
   */
  std::unique_ptr<ExprNode> parseAddSub();

  /**
   * @brief Parses a multiplicative expression (*, /, %).
   *
   * Grammar:
   * @code
   * mulDivMod -> unary ( ( "*" | "/" | "%" ) unary )*
   * @endcode
   *
   * @return A unique_ptr to the parsed ExprNode.
   */
  std::unique_ptr<ExprNode> parseMulDivMod();

  /**
   * @brief Parses a unary expression (unary -, not).
   *
   * Grammar:
   * @code
   * unary -> ( "-" | "not" ) unary | primary
   * @endcode
   *
   * @return A unique_ptr to the parsed ExprNode.
   */
  std::unique_ptr<ExprNode> parseUnary();

  /**
   * @brief Parses a primary expression (literals, identifiers, grouped
   * expressions, function calls).
   *
   * Grammar:
   * @code
   * primary -> LIT_INT
   *          | LIT_FLOAT
   *          | LIT_STRING
   *          | "true"
   *          | "false"
   *          | IDENTIFIER ( "(" ( expr ( "," expr )* )? ")" )?
   *          | "(" expr ")"
   * @endcode
   *
   * @return A unique_ptr to the parsed ExprNode.
   */
  std::unique_ptr<ExprNode> parsePrimary();

  /**
   * @brief Parses a type annotation (e.g. `int`, `float`, `bool`, `string`,
   * `void`).
   *
   * Grammar:
   * @code
   * typeAnnotation -> "int" | "float" | "bool" | "string" | "void"
   * @endcode
   *
   * @return The parsed type name string.
   */
  std::string parseTypeAnnotation();

  /**
   * @brief Maps a binary operator TokenType to its string representation.
   * @param type The binary operator TokenType.
   * @return A string representing the operator lexeme.
   */
  std::string tokenLexForBinary(TokenType type) const;

  /**
   * @brief Peeks at the token at the current position or slightly ahead.
   * @param ahead Number of tokens ahead to peek.
   * @return A reference to the peeked Token.
   */
  const Token &peek(size_t ahead = 0) const;

  /**
   * @brief Gets the token immediately preceding the current position.
   * @return The previous Token.
   */
  Token previous() const;

  /**
   * @brief Checks if all tokens have been processed.
   * @return true if reached EOF, false otherwise.
   */
  bool isAtEnd() const;

  /**
   * @brief Advances the parsing position by one token and returns the previous
   * token.
   * @return The Token advanced past.
   */
  Token advance();

  /**
   * @brief Checks if the current token matches the specified type.
   * @param type The TokenType to check.
   * @return true if matches, false otherwise.
   */
  bool check(TokenType type) const;

  /**
   * @brief Checks if the current token matches the specified type, and advances
   * if it does.
   * @param type The TokenType to match.
   * @return true if matched and advanced, false otherwise.
   */
  bool match(TokenType type);

  /**
   * @brief Consumes a token of the expected type, or reports a syntax error.
   * @param type The expected TokenType.
   * @param msg The error message to report on mismatch.
   * @return The consumed Token.
   */
  Token consume(TokenType type, std::string msg);

  /**
   * @brief Reports a syntax error.
   * @param tok The token where the error occurred.
   * @param msg Description of the syntax error.
   */
  void reportError(const Token &tok, const std::string &msg);

  /**
   * @brief Skips consecutive newline tokens.
   */
  void skipNewLines();
};

#endif // CYNIDE_PARSER_H